name: mentionable_text_field_example
description: An example of mentionable_text_field package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  mention_popup:
    path: ../../
  rxdart: ^0.27.5
  flutter_portal: ^1.1.4
  flutter_keyboard_visibility: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
